### ISSUE TITLE
Minimal usage example?

### ISSUE THREAD

**Issue by Anonyfox** [egoist/vbuild-karma#1]
Could you provide a minimal example for a single unittest? I added `vbuild-karma`, created `test/unit` directories, and started everything with `vbuild -c vbuild.karma.js` with the default `vbuild.karma.js` file. 

It seems to start phantom and then hangs indefinitely: 

````sh
22 02 2017 11:52:14.268:WARN [karma]: No captured browser, open http://localhost:5001/
22 02 2017 11:52:14.280:WARN [karma]: Port 5001 in use
22 02 2017 11:52:14.281:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:5002/
22 02 2017 11:52:14.281:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
22 02 2017 11:52:14.286:INFO [launcher]: Starting browser PhantomJS
22 02 2017 11:52:14.834:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket Sl9vyAtY6S4d4WoHAAAA with id 2413250

PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.001 secs / 0 secs)
````

How do I continue from here? At least the error is correct, in that I don't have any test files written yet.

**Comment by egoist** [comment]
I think you can start writing tests like how the official guide suggests? 

https://vuejs.org/v2/guide/unit-testing.html

**Comment by Anonyfox** [comment]
Alright, this works! my fault, thank you. 

But it seems to hang indefinitely on test failure, still. Do I have to configure something here? This would break our CI systems unfortunately.

**Comment by egoist** [comment]
I think on CI the `singleRun` mode will be used?  https://github.com/egoist/vbuild-karma/blob/master/index.js#L24

**Comment by Anonyfox** [comment]
works, thank you :)
